import type {
  DashboardStats,
  AlertListResponse,
  TransactionListResponse,
  Transaction,
  RiskAssessment,
  NetworkStats,
  ModelStatus,
  RiskFeedEvent
} from '../types';

export const mockDashboardStats: DashboardStats = {
  total_transactions: 18450,
  blocked_transactions: 320,
  active_alerts: 14,
  critical_alerts: 3,
  average_risk_score: 31.8,
  decision_breakdown: {
    allow: 15210,
    monitor: 2140,
    step_up: 780,
    block: 320,
  },
  risk_timeline: [
    { timestamp: '10:00', risk_score: 18, decision: 'ALLOW' },
    { timestamp: '10:15', risk_score: 24, decision: 'ALLOW' },
    { timestamp: '10:30', risk_score: 82, decision: 'BLOCK' },
    { timestamp: '10:45', risk_score: 45, decision: 'MONITOR' },
    { timestamp: '11:00', risk_score: 72, decision: 'STEP-UP' },
    { timestamp: '11:15', risk_score: 30, decision: 'ALLOW' },
    { timestamp: '11:30', risk_score: 91, decision: 'BLOCK' },
    { timestamp: '11:45', risk_score: 28, decision: 'ALLOW' },
    { timestamp: '12:00', risk_score: 36, decision: 'ALLOW' },
  ],
};

export const mockTransactions: Transaction[] = [
  {
    id: 'tx_mock_001',
    transaction_id: 'TXN-9021-849201',
    user_id: 'usr_8921',
    merchant_id: 'merch_pay_stripe',
    amount: 94500,
    currency: 'INR',
    ip_address: '194.26.29.112',
    device_id: 'dev_fingerprint_x89',
    country: 'RU',
    payment_method: 'credit_card',
    failed_attempts: 6,
    transaction_frequency: 18,
    account_age_days: 2,
    previous_transaction_avg: 1200,
    previous_transaction_count: 1,
    is_new_device: true,
    is_new_ip: true,
    status: 'COMPLETED',
    decision: 'BLOCK',
    scenario_label: 'carding_attack',
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: 'tx_mock_002',
    transaction_id: 'TXN-4192-384910',
    user_id: 'usr_4412',
    merchant_id: 'merch_amazon_in',
    amount: 14200,
    currency: 'INR',
    ip_address: '103.21.144.12',
    device_id: 'dev_apple_iphone15',
    country: 'IN',
    payment_method: 'upi',
    failed_attempts: 1,
    transaction_frequency: 4,
    account_age_days: 180,
    previous_transaction_avg: 4500,
    previous_transaction_count: 42,
    is_new_device: true,
    is_new_ip: false,
    status: 'COMPLETED',
    decision: 'STEP-UP',
    scenario_label: 'high_amount_ratio',
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'tx_mock_003',
    transaction_id: 'TXN-1823-749102',
    user_id: 'usr_1092',
    merchant_id: 'merch_uber_ride',
    amount: 480,
    currency: 'INR',
    ip_address: '49.36.12.88',
    device_id: 'dev_samsung_s23',
    country: 'IN',
    payment_method: 'upi',
    failed_attempts: 0,
    transaction_frequency: 1,
    account_age_days: 490,
    previous_transaction_avg: 520,
    previous_transaction_count: 118,
    is_new_device: false,
    is_new_ip: false,
    status: 'COMPLETED',
    decision: 'ALLOW',
    scenario_label: 'normal_payment',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'tx_mock_004',
    transaction_id: 'TXN-7731-992014',
    user_id: 'usr_7812',
    merchant_id: 'merch_crypto_binance',
    amount: 65000,
    currency: 'INR',
    ip_address: '185.220.101.5',
    device_id: 'dev_tor_browser_win',
    country: 'DE',
    payment_method: 'netbanking',
    failed_attempts: 4,
    transaction_frequency: 12,
    account_age_days: 5,
    previous_transaction_avg: 2100,
    previous_transaction_count: 3,
    is_new_device: true,
    is_new_ip: true,
    status: 'COMPLETED',
    decision: 'BLOCK',
    scenario_label: 'tor_exit_node',
    timestamp: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
  },
  {
    id: 'tx_mock_005',
    transaction_id: 'TXN-3829-110293',
    user_id: 'usr_3910',
    merchant_id: 'merch_zomato_order',
    amount: 1250,
    currency: 'INR',
    ip_address: '106.195.34.19',
    device_id: 'dev_pixel_8_pro',
    country: 'IN',
    payment_method: 'credit_card',
    failed_attempts: 0,
    transaction_frequency: 2,
    account_age_days: 720,
    previous_transaction_avg: 1100,
    previous_transaction_count: 245,
    is_new_device: false,
    is_new_ip: false,
    status: 'COMPLETED',
    decision: 'ALLOW',
    scenario_label: 'normal_payment',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
];

export const mockTransactionListResponse: TransactionListResponse = {
  total: mockTransactions.length,
  page: 1,
  page_size: 50,
  items: mockTransactions,
};

export const mockAlerts: AlertListResponse = {
  total: 3,
  items: [
    {
      id: 'alt_001',
      title: 'Automated Credential Stuffing & High Velocity Carding',
      message: 'IP flagged on threat intelligence blocklist. 6 consecutive failed attempts observed within 30s.',
      alert_type: 'FRAUD_BURST',
      severity: 'CRITICAL',
      status: 'OPEN',
      transaction_id: 'TXN-9021-849201',
      is_resolved: false,
      escalated_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
      resolved_at: null,
      created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    },
    {
      id: 'alt_002',
      title: 'Tor Exit Node & Geolocation Mismatch',
      message: 'Connection originated from known privacy proxy with velocity spike in cryptocurrency checkout.',
      alert_type: 'NETWORK_ANOMALY',
      severity: 'CRITICAL',
      status: 'OPEN',
      transaction_id: 'TXN-7731-992014',
      is_resolved: false,
      escalated_at: null,
      resolved_at: null,
      created_at: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    },
    {
      id: 'alt_003',
      title: 'Spike in Transaction Amount vs Historic Baseline',
      message: 'Transaction is 3.15x higher than 90-day moving average from a new mobile hardware profile.',
      alert_type: 'AMOUNT_VELOCITY',
      severity: 'HIGH',
      status: 'OPEN',
      transaction_id: 'TXN-4192-384910',
      is_resolved: false,
      escalated_at: null,
      resolved_at: null,
      created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    },
  ],
};

export const mockRiskAssessment: RiskAssessment = {
  id: 'ra_mock_001',
  transaction_id: 'TXN-9021-849201',
  transaction_uuid: '09a8f271-8b92-4f32-8cb2-8329bce01982',
  risk_score: 92,
  decision: 'BLOCK',
  confidence: 0.94,
  transaction_score: 95,
  behavioral_score: 89,
  network_score: 88,
  ml_anomaly_score: 94,
  ml_supervised_score: 92,
  breakdown: {
    transaction: 95,
    behavioral: 89,
    network: 88,
    ml_anomaly: 94,
    ml_supervised: 92,
  },
  risk_factors: [
    {
      factor: 'amount_ratio',
      description: 'Transaction amount represents a 78.8x surge above user history',
      severity: 'CRITICAL',
      contribution: 42,
    },
    {
      factor: 'failed_attempts',
      description: '6 consecutive authentication failures observed prior to request',
      severity: 'CRITICAL',
      contribution: 28,
    },
    {
      factor: 'account_age_days',
      description: 'Account opened less than 48 hours ago',
      severity: 'HIGH',
      contribution: 16,
    },
    {
      factor: 'is_new_device',
      description: 'First transaction observed on unverified device signature',
      severity: 'MEDIUM',
      contribution: 9,
    },
  ],
  shap_values: {
    amount_ratio: 0.42,
    failed_attempts: 0.28,
    account_age_days: 0.16,
    is_new_device: 0.09,
    packet_rate: 0.05,
  },
  llm_explanation:
    'Extreme fraud probability detected. Transaction amount (₹94,500) represents a 78.8x surge above user historical activity on an account created less than 48 hours ago. Combined with 6 failed authentication attempts and a known threat IP, the system executed an automated BLOCK.',
  rule_flags: {
    amount_spike: true,
    auth_velocity_breached: true,
    unrecognized_device: true,
  },
  ml_fallback: false,
  created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
};

export const mockNetworkStats: NetworkStats = {
  total_events: 12450,
  suspicious_events: 138,
  average_request_rate: 28.4,
  suspicious_ips: ['194.26.29.112', '185.220.101.5', '45.154.255.89'],
  request_timeline: [
    { timestamp: '10:00', request_rate: 12.4, is_suspicious: false },
    { timestamp: '10:15', request_rate: 14.8, is_suspicious: false },
    { timestamp: '10:30', request_rate: 135.2, is_suspicious: true },
    { timestamp: '10:45', request_rate: 18.0, is_suspicious: false },
    { timestamp: '11:00', request_rate: 98.4, is_suspicious: true },
    { timestamp: '11:15', request_rate: 15.1, is_suspicious: false },
    { timestamp: '11:30', request_rate: 174.0, is_suspicious: true },
    { timestamp: '11:45', request_rate: 22.3, is_suspicious: false },
  ],
};

export const mockModelStatus: ModelStatus = {
  ml_service_healthy: true,
  isolation_forest: {
    loaded: true,
    features: ['amount', 'amount_ratio', 'failed_attempts', 'transaction_frequency'],
  },
  xgboost: {
    loaded: true,
    shap_available: true,
    features: ['amount', 'failed_attempts', 'is_new_device', 'packet_rate', 'account_age_days'],
  },
  fallback_active: false,
};

export const generateMockRiskFeedEvent = (): RiskFeedEvent => {
  const scenarios = [
    {
      decision: 'ALLOW' as const,
      amount: Math.floor(Math.random() * 2000) + 200,
      risk_score: Math.floor(Math.random() * 25) + 10,
      factor: 'Consistent device fingerprint & low amount ratio',
    },
    {
      decision: 'MONITOR' as const,
      amount: Math.floor(Math.random() * 8000) + 3000,
      risk_score: Math.floor(Math.random() * 20) + 40,
      factor: 'Slightly elevated transaction frequency',
    },
    {
      decision: 'STEP-UP' as const,
      amount: Math.floor(Math.random() * 25000) + 12000,
      risk_score: Math.floor(Math.random() * 15) + 65,
      factor: 'New device hardware identifier detected',
    },
    {
      decision: 'BLOCK' as const,
      amount: Math.floor(Math.random() * 80000) + 40000,
      risk_score: Math.floor(Math.random() * 15) + 85,
      factor: 'Multiple failed attempts & blacklisted threat IP',
    },
  ];

  const pick = scenarios[Math.floor(Math.random() * scenarios.length)];
  const idNum = Math.floor(1000 + Math.random() * 9000);

  return {
    type: 'risk_assessment',
    transaction_id: `TXN-${idNum}-${Math.floor(100000 + Math.random() * 900000)}`,
    amount: pick.amount,
    currency: 'INR',
    user_id: `usr_${Math.floor(1000 + Math.random() * 9000)}`,
    ip_address: `${Math.floor(Math.random() * 200) + 10}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`,
    risk_score: pick.risk_score,
    decision: pick.decision,
    confidence: +(0.85 + Math.random() * 0.12).toFixed(2),
    top_factor: pick.factor,
    timestamp: new Date().toISOString(),
  };
};
